EMAIL = "email@gmail.com"
PASSWORD = "pw"
SMTP_SERVER = "imap.gmail.com"
EMAIL_TO = ", ".join([None, None])
EMAIL_FROM = EMAIL
PASSWORD_FROM = PASSWORD
FETCH_TIME = 24 * 3600 # fetch mails that are no older than this value (seconds)
FETCH_LABEL = "inbox" # label from which to fetch emails
DEST_LANGUAGE = "en"
DEST_CURRENCY = "PLN"